version: 2

dist: /tmp/goreleaser-dist

release:
  prerelease: auto

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=1
    ldflags:
      - -X main.version=v{{.Version}} -s -w -linkmode external -extldflags "-static"
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    overrides:
      - goos: linux
        goarch: amd64
        env:
          - CC=x86_64-linux-gnu-gcc
          - CXX=x86_64-linux-gnu-g++
      - goos: linux
        goarch: arm64
        env:
          - CC=aarch64-linux-gnu-gcc
          - CXX=aarch64-linux-gnu-g++
      - goos: darwin
        goarch: amd64
        env:
          - CC=o64-clang
          - CXX=o64-clang++
        ldflags:
          - -X main.version=v{{.Version}} -s -w
      - goos: darwin
        goarch: arm64
        env:
          - CC=oa64-clang
          - CXX=oa64-clang++
        ldflags:
          - -X main.version=v{{.Version}} -s -w
      - goos: windows
        goarch: amd64
        env:
          - CC=x86_64-w64-mingw32-gcc
          - CXX=x86_64-w64-mingw32-g++

archives:
  - formats:
      - tar.gz
    name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - none*

snapshot:
  version_template: "{{ .Version }}"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
