/*
Aura is an agentic coding CLI assistant.

Usage:

	aura [command] [flags]

Use "aura --help" for more information.
*/
package main

import (
	"context"
	"errors"
	"fmt"
	"os"

	"github.com/idelchi/aura/internal/cli"
)

// version is the application version injected at build time.
var version = "unknown - unofficial & generated by unknown"

// main is the entry point of the application.
func main() {
	cli.SetEmbeddedConfig(embeddedConfig)

	if err := cli.Execute(version); err != nil {
		if !errors.Is(err, context.Canceled) {
			fmt.Fprintln(os.Stderr, err)
		}

		os.Exit(1)
	}

	os.Exit(0)
}
