sandbox:
  enabled: true
  restrictions:
    ro:
      - /bin
      - /etc
      - /home
      - /lib
      - /lib64
      - /opt
      - /run
      - /sbin
      - /tmp
      - /usr
      - /var
    rw:
      - /tmp
      - $HOME/.cache
      - $HOME/go
      - /dev/null
