title: Aura
description: "Agentic coding CLI"
baseurl: "/aura"
url: "https://idelchi.github.io"

remote_theme: just-the-docs/just-the-docs@v0.10.1

plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-default-layout
  - kramdown-syntax-coderay

color_scheme: light

aux_links:
  GitHub:
    - "//github.com/idelchi/aura"
  Docs:
    - "//pkg.go.dev/github.com/idelchi/aura"

aux_links_new_tab: true

nav_sort: case_sensitive

footer_content: "Copyright &copy; 2026 idelchi. Distributed under the MIT License."

logo: "/assets/images/aura.png"

favicon_ico: "/assets/images/aura.ico"

back_to_top: true
back_to_top_text: "Back to top"

enable_copy_code_button: true

include:
  - _versions
